"""Generate an OT-2 protocol from dashboard toggles (upload in the Opentrons App)."""

from __future__ import annotations

from typing import Any, Dict, List


DEFAULT_OT: Dict[str, Any] = {
    "replicates": 7,
    "DMAm_volumes": [9.36, 1.83, 50, 50],
    "AMPS_volumes": [62.72, 0, 50, 50],
    "PBS_volumes": [185.92, 152.17, 50, 50],
    "crosslinker_volumes": [12, 96, 50, 50],
    "photoinitiator_volumes": [30, 30, 50, 50],
    "dispense_DMAm": False,
    "dispense_AMPS": False,
    "dispense_crosslinker": False,
    "dispense_photoinitiator": False,
    "dispense_PBS": False,
    "pipette_mix": False,
    "stir_plate_wait": False,
    "stir_wait_s": 120,
    "transfer_to_testplate": False,
    "uv_stand_move": True,
}


def _nums(values: List[Any], fallback: List[float]) -> str:
    if not values:
        values = fallback
    out = []
    for v in values:
        try:
            out.append(str(float(v)))
        except (TypeError, ValueError):
            out.append("0")
    return "[" + ", ".join(out) + "]"


def generate_protocol(settings: Dict[str, Any] | None = None) -> str:
    s = {**DEFAULT_OT, **(settings or {})}
    replicates = int(s.get("replicates") or 7)
    stir_wait_s = int(s.get("stir_wait_s") or 120)

    dispense_calls = []
    if s.get("dispense_DMAm"):
        dispense_calls.append('    dispense_reagent(DMAm_replicates, DMAm_stock, "DMAm")')
    if s.get("dispense_AMPS"):
        dispense_calls.append('    dispense_reagent(AMPS_replicates, AMPS_stock, "AMPS")')
    if s.get("dispense_crosslinker"):
        dispense_calls.append(
            '    dispense_reagent(crosslinker_replicates, crosslinker_stock, "crosslinker")'
        )
    if s.get("dispense_photoinitiator"):
        dispense_calls.append(
            '    dispense_reagent(photoinitiator_replicates, photoinitiator_stock, "photoinitiator")'
        )
    if s.get("dispense_PBS"):
        dispense_calls.append('    dispense_reagent(PBS_replicates, PBS_stock, "PBS")')
    if not dispense_calls:
        dispense_block = "    protocol.comment('Reagent dispense skipped.')\n"
    else:
        dispense_block = "\n".join(dispense_calls) + "\n"

    if s.get("pipette_mix"):
        mix_block = """    if total_volume >= 200:
        mix_pipette = pipette_1000
    else:
        mix_pipette = pipette_200
    for i in range(total_wells):
        mix_pipette.pick_up_tip()
        mix_pipette.mix(10, total_volume / 1.667, wellplate1.wells()[i].bottom(1))
        mix_pipette.drop_tip()
"""
    else:
        mix_block = "    protocol.comment('Pipette mix skipped.')\n"

    if s.get("stir_plate_wait"):
        stir_block = f"    protocol.delay({stir_wait_s})\n"
    else:
        stir_block = "    protocol.comment('Stir-plate wait skipped.')\n"

    if s.get("transfer_to_testplate"):
        transfer_block = """    for i in range(total_wells):
        pipette_200.pick_up_tip()
        pipette_200.mix(10, 200, wellplate1.wells()[i].bottom(1))
        for j in range(max(replicates - 2, 0)):
            dest_index = i + j * 5
            pipette_200.aspirate(volume=95.0, location=wellplate1.wells()[i].bottom(z=1), rate=10)
            pipette_200.touch_tip(location=wellplate1.wells()[i], radius=0.9, v_offset=-1, speed=50)
            pipette_200.dispense(volume=95.0, location=wellplate_test.wells()[dest_index].top(), rate=10)
            pipette_200.blow_out(location=wellplate_test.wells()[dest_index].top())
            protocol.delay(2)
        pipette_200.drop_tip()
"""
    else:
        transfer_block = "    protocol.comment('Transfer to test plate skipped.')\n"

    if s.get("uv_stand_move"):
        uv_block = """    pipette_1000.pick_up_tip(tip1000.wells()[95])
    custom_pickup1(UV_stand["E1"].bottom(z=1), 0, 0, 0)
    custom_dropoff1(wellplate_test["A1"].bottom(z=1), 0, 0, 0)
    pipette_1000.pick_up_tip(tip1000.wells()[95])
    custom_pickup2(wellplate_test["A1"].bottom(z=1), 0, 0, 0)
    custom_dropoff2(UV_stand["E1"].bottom(z=1), 0, 0, 0)
"""
    else:
        uv_block = "    protocol.comment('UV-stand pickup/dropoff skipped.')\n"

    return f'''from opentrons import protocol_api
from opentrons.types import Point
from time import sleep

# Generated by the Automated Indenter dashboard. Import this file in the Opentrons App.
# Custom labware names (allen_8_wellplate_20000ul, testwell) must already exist on the OT-2.
# This protocol does not turn the UV lamp serial line on or off.

requirements = {{
    "apiLevel": "2.18"
}}


def run(protocol: protocol_api.ProtocolContext):
    replicates = {replicates}
    total_volume = 300 * replicates

    DMAm_volumes = {_nums(s.get("DMAm_volumes"), DEFAULT_OT["DMAm_volumes"])}
    AMPS_volumes = {_nums(s.get("AMPS_volumes"), DEFAULT_OT["AMPS_volumes"])}
    PBS_volumes = {_nums(s.get("PBS_volumes"), DEFAULT_OT["PBS_volumes"])}
    crosslinker_volumes = {_nums(s.get("crosslinker_volumes"), DEFAULT_OT["crosslinker_volumes"])}
    photoinitiator_volumes = {_nums(s.get("photoinitiator_volumes"), DEFAULT_OT["photoinitiator_volumes"])}

    DMAm_replicates = [v * replicates for v in DMAm_volumes]
    AMPS_replicates = [v * replicates for v in AMPS_volumes]
    crosslinker_replicates = [v * replicates for v in crosslinker_volumes]
    photoinitiator_replicates = [v * replicates for v in photoinitiator_volumes]
    PBS_replicates = [v * replicates for v in PBS_volumes]

    total_wells = len(DMAm_volumes)
    exp_no = list(range(total_wells))

    tip1000 = protocol.load_labware("opentrons_96_filtertiprack_1000ul", "8")
    pipette_1000 = protocol.load_instrument("p1000_single_gen2", "right", tip_racks=[tip1000])
    tip200 = protocol.load_labware("opentrons_96_filtertiprack_200ul", "9")
    pipette_200 = protocol.load_instrument("p300_single", "left", tip_racks=[tip200])

    def pipette_select(volume):
        if volume >= 200:
            return pipette_1000
        return pipette_200

    stock = protocol.load_labware("allen_8_wellplate_20000ul", "6")
    DMAm_stock = stock["A1"]
    AMPS_stock = stock["A2"]
    crosslinker_stock = stock["A3"]
    photoinitiator_stock = stock["A4"]
    PBS_stock = stock["B1"]

    wellplate1 = protocol.load_labware("nest_96_wellplate_2ml_deep", "5")
    wellplate_test = protocol.load_labware("testwell", "4")
    UV_stand = protocol.load_labware("testwell", "10")

    def custom_move(location, x, y, z):
        loc_offset = location.move(Point(x, y, z))
        pipette_1000.move_to(loc_offset, minimum_z_height=50)

    def custom_pickup1(location, x, y, z):
        custom_move(location, x + 8, y - 31, z + 17)
        sleep(2)
        custom_move(location, x + 8, y - 31, z + 12)
        sleep(2)
        custom_move(location, x + 8, y - 31, z + 7)

    def custom_dropoff1(location, x, y, z):
        loc_offset = location.move(Point(x + 8, y - 21, z + 23))
        sleep(2)
        pipette_1000.drop_tip(loc_offset)

    def custom_pickup2(location, x, y, z):
        custom_move(location, x + 8, y - 21, z + 17)
        sleep(2)
        custom_move(location, x + 8, y - 21, z + 12)
        sleep(2)
        custom_move(location, x + 8, y - 21, z + 7)

    def custom_dropoff2(location, x, y, z):
        loc_offset = location.move(Point(x + 8, y - 31, z + 23))
        sleep(2)
        pipette_1000.drop_tip(loc_offset)

    def dispense_reagent(volume_list, source, reagent_name):
        EPS = 1e-6
        pipette_200.pick_up_tip()
        pipette_1000.pick_up_tip()
        for i in exp_no:
            if volume_list[i] > EPS:
                pipette = pipette_select(volume_list[i])
                pipette.aspirate(volume=volume_list[i], location=source.bottom(z=1), rate=10)
                pipette.touch_tip(location=source, radius=0.9, v_offset=-1, speed=50)
                pipette.dispense(volume=volume_list[i], location=wellplate1.wells()[i].top(z=0), rate=10)
                pipette.blow_out(location=wellplate1.wells()[i].top(z=0))
                protocol.delay(2)
                pipette.touch_tip(location=wellplate1.wells()[i], radius=0.9, v_offset=-0.5, speed=50)
        pipette_1000.drop_tip()
        pipette_200.drop_tip()
        protocol.comment(f"Dispensed {{reagent_name}} to all wells.")

    pipette_200.flow_rate.aspirate = 110
    pipette_200.flow_rate.dispense = 110
    pipette_200.flow_rate.blow_out = 50
    pipette_1000.flow_rate.aspirate = 110
    pipette_1000.flow_rate.dispense = 110
    pipette_1000.flow_rate.blow_out = 50

{dispense_block}
{mix_block}
{stir_block}
{transfer_block}
{uv_block}
'''
